# Name of your application. Used to uniquely configure containers.
service: webcams

# Name of the container image.
image: katafractari/webcams

# Deploy to these servers.
servers:
  web:
    - katafractari

proxy:
  ssl: false
  host: webcams.parabola.si
  app_port: 3000

# Credentials for your image host.
registry:
  username: katafractari
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup for Raspberry Pi 4 (ARM64).
builder:
  arch: arm64

# Environment variables for the webcam application
env:
  clear:
    NODE_ENV: production
    PORT: 3000
    SHEET_RANGE: A2:B
  secret:
    - GOOGLE_SHEET_ID
    - GOOGLE_SHEETS_API_KEY
